name: medireminder_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  intl: ^0.20.2
  uuid: ^4.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  provider: ^6.1.5+1
  firebase_auth: ^6.1.0
  flutter_signin_button: ^2.1.1
  firebase_database: ^12.0.2
  cloud_firestore: ^6.0.2

  flutter_local_notifications: ^17.2.2
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  timezone: any
flutter:
  uses-material-design: true

  assets:
    - assets/images/medicine.png
    - assets/images/calendar_pill.jpg
    - assets/images/hinh1.png
    - assets/images/anhuongthuoc.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Italic.ttf