// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7j1IUvaS48Z-MHDdB6y5s5ht0XAhkcE',
    appId: '1:481308140097:web:b6de34125354a002831cc0',
    messagingSenderId: '481308140097',
    projectId: 'iotmedicalbox',
    authDomain: 'iotmedicalbox.firebaseapp.com',
    databaseURL: 'https://iotmedicalbox-default-rtdb.firebaseio.com',
    storageBucket: 'iotmedicalbox.firebasestorage.app',
    measurementId: 'G-YPH62ELRF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-X5Wr3cu5tDN4TNgD492tx-N4hHR0fM',
    appId: '1:481308140097:android:53b8d7173dfaf2c3831cc0',
    messagingSenderId: '481308140097',
    projectId: 'iotmedicalbox',
    databaseURL: 'https://iotmedicalbox-default-rtdb.firebaseio.com',
    storageBucket: 'iotmedicalbox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWj0VE34Z1erSeFqjf29lo180veCWVWMY',
    appId: '1:481308140097:ios:3668a50e4332bb70831cc0',
    messagingSenderId: '481308140097',
    projectId: 'iotmedicalbox',
    databaseURL: 'https://iotmedicalbox-default-rtdb.firebaseio.com',
    storageBucket: 'iotmedicalbox.firebasestorage.app',
    androidClientId: '481308140097-eeef0h7568mi7u7duihb30t7tber583u.apps.googleusercontent.com',
    iosClientId: '481308140097-hnkra67fjami1c6s894m5qj95d4n6s6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.medireminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWj0VE34Z1erSeFqjf29lo180veCWVWMY',
    appId: '1:481308140097:ios:3668a50e4332bb70831cc0',
    messagingSenderId: '481308140097',
    projectId: 'iotmedicalbox',
    databaseURL: 'https://iotmedicalbox-default-rtdb.firebaseio.com',
    storageBucket: 'iotmedicalbox.firebasestorage.app',
    androidClientId: '481308140097-eeef0h7568mi7u7duihb30t7tber583u.apps.googleusercontent.com',
    iosClientId: '481308140097-hnkra67fjami1c6s894m5qj95d4n6s6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.medireminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz7j1IUvaS48Z-MHDdB6y5s5ht0XAhkcE',
    appId: '1:481308140097:web:fba2761b4189729b831cc0',
    messagingSenderId: '481308140097',
    projectId: 'iotmedicalbox',
    authDomain: 'iotmedicalbox.firebaseapp.com',
    databaseURL: 'https://iotmedicalbox-default-rtdb.firebaseio.com',
    storageBucket: 'iotmedicalbox.firebasestorage.app',
    measurementId: 'G-DKC60Q2N41',
  );

}